// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqaxNwwZF5W5Oy2kw1CtQdnrDKlNJmImc',
    appId: '1:562454569704:web:862b97101fa061cf36df5d',
    messagingSenderId: '562454569704',
    projectId: 'ppdb-project-b213e',
    authDomain: 'ppdb-project-b213e.firebaseapp.com',
    storageBucket: 'ppdb-project-b213e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi1KemF2Y5sItfL6W5mXGN45X0lWPRTPY',
    appId: '1:562454569704:android:a783d2b79ee84b5836df5d',
    messagingSenderId: '562454569704',
    projectId: 'ppdb-project-b213e',
    storageBucket: 'ppdb-project-b213e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqaxNwwZF5W5Oy2kw1CtQdnrDKlNJmImc',
    appId: '1:562454569704:web:970ecd5f977e0b9a36df5d',
    messagingSenderId: '562454569704',
    projectId: 'ppdb-project-b213e',
    authDomain: 'ppdb-project-b213e.firebaseapp.com',
    storageBucket: 'ppdb-project-b213e.firebasestorage.app',
  );
}
